[window]
decorations = "Transparent"
option_as_alt = "None"
padding.x = 30
padding.y = 30


[scrolling]
history = 0


[colors]
bright.black = "0x1d1d1d"
bright.blue = "0xa0b9d8"
bright.cyan = "0x7dc2c7"
bright.green = "0x92c47e"
bright.magenta = "0xc6aed7"
bright.red = "0xfe9f7c"
bright.white = "0xfffefe"
bright.yellow = "0xd2b45f"

normal.black = "0x000000"
normal.blue = "0x8296b0"
normal.cyan = "0x659ea2"
normal.green = "0x76a065"
normal.magenta = "0xa18daf"
normal.red = "0xcf8164"
normal.white = "0xb5b4c9"
normal.yellow = "0xab924c"

primary.background = "0x000000"
primary.foreground = "0xb5b4c9"


[font]
size = 16.0

bold.family = "Inconsolata"
bold.style = "Bold"

bold_italic.family = "Inconsolata"
bold_italic.style = "Regular Italic"

italic.family = "Inconsolata"
italic.style = "Italic"

normal.family = "Inconsolata"
normal.style = "Regular"

offset.y = 5


[[hints.enabled]]
command = "open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"
