

export EDITOR=/usr/bin/vim


export PATH="/usr/local/mysql/bin:$PATH"



alias apacheEdit='sudo vim /etc/apache2/httpd.conf'      # apacheEdit:       Edit httpd.conf
alias apacheRestart='sudo apachectl graceful'


alias ytdl='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"'
alias html2pdf="wkhtmltopdf"

alias tempus='~/tempus/tempus'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
