xrdb $HOME/.Xresources
start-pulseaudio-x11 &
setxkbmap no

while true; do
	getDate() {
		acpi
		currentTime=`date +"%d-%m %H:%M"`
		echo $currentTime
	}
	xsetroot -name "  $(getDate)  "
	sleep 1
done &

~/.fehbg &
exec dwm
